version: '3'

services:
  react:
    container_name: bh-react-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - "./:/app"
      - "/app/node_modules"
    environment:
      - "NODE_ENV=staging"
