# pull official base image
FROM node:16.14.0-alpine

# set working directory
WORKDIR /app

COPY package*.json ./

RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

EXPOSE 3000

CMD ["npm", "start"]

